### ISSUE TITLE
Client side only code

### ISSUE THREAD

**Issue by rohanbam** [frandiox/vitessedge-template#4]
How can I have code that executes client side only in a vue component? Specifically, I want to use three.js in a vue component and want it to not be packaged in the worker script but only import and run client side.

**Comment by frandiox** [comment]
Have a look at the docs here: https://vitedge.js.org/conditional-rendering.html

You can probably combine `<ClientOnly>` and install three.js using a CDN instead of an NPM dependency, for example. That way you make sure it's downloaded only in browser.

**Comment by rohanbam** [comment]
Hey frandiox, Sorry for asking in a closed issue. I did not find how to reopen it but thought the question was relevant to this issue. I hope that is alright.

I have the following component hierarchy,

Component1
         <ClientOnly> Component2 </ClientOnly>

Inside Component2, when I try to do
<script type ="module">
import * as THREE from https://unpkg.com/three@0.136.0/build/three.module.js
</script>

I get the following error
[vite] Internal server error: Cannot find module 'https://unpkg.com/three@0.136.0/build/three.module.js'
I get this error for any CDN URL that I try to import. The import works if I try to load a module from local directories instead of CDN.

Does this mean that the ClientOnly component is not working as expected?
Is there anything that needs to be configured in Vite so that I can import modules from CDN URLs?
